### PR TITLE
Updated UG & Test for FindCommand

### PR DESCRIPTION
**Pull request by nealetham**
This is a follow up from #31.

## Documentation
- [x] User Guide
- [x] Developer Guide
- [x] Javadocs

### Sections updated under UG

- Find command

### Sections updated under DG

- NIL

### Classes with Javadocs update

- NIL

---

### Sections updated

- NameContainsKeywordsPredicateTest - Tests the functionality of the partial keyword matching
- FindCommandTest - Unit tests the find command as integrated into the model

### CODE REVIEW

**Review by nseah21 — APPROVED** [review]
LGTM

**Review by jq1836 — COMMENTED** [review]
Looks good, apart from one possible test which is a mix of a non-matching keyword, followed by a matching keyword. e.g. A list with Alice Carol, with a find li role.

Anyways, this will likely be changed drastically by PR #72, so we'll likely be making changes to the tests. Appreciate the work though!

**Review by nareus — APPROVED** [review]
LGTM! The tests seem to be sufficient to test the working of the classes for the find command feature. The user guide seems to be accurate as well

**Review by jq1836 — APPROVED** [review]
LGTM!

**Pull request merged**
