### PR TITLE
Add support for find command (from AB3) to perform substring search

### PR DESCRIPTION
**Pull request by nealetham**
As per the discussion, I've updated the find command to perform substring search. The find command will no longer require strict matching between the name and keywords.

If I'm not wrong, the changes would not have any effect of any other logic components of the application.

Given that this is the first feature PR, this is a reminder of the following reviewer roles:
Alvin -> Documentation
Nicholas -> Code quality
Naren -> Testing

*EDIT: Forgive me, you can ignore the changes in the UserGuide.md and DeveloperGuide.md

### CODE REVIEW

**Review by jq1836 — COMMENTED** [review]
In this case, the only time the `StringUtil`'s `containsWordIgnoreCase` method was used is in the find command, so it is fine altering it. However, do take note that sometimes altering stuff like this may lead to unwanted side effects.

Great job though! 👍

P.S. you might get some merge conflicts when updating branch, due to the DG and UG being a part of your current branch.

**Review by nseah21 — APPROVED** [review]
LGTM!

**Review by alvinjiang1 — APPROVED** [review]
LGTM👌

**Review by nareus — APPROVED** [review]
This looks good Neale! The tests check for a broad range of cases so they should be sufficient. If you have time, you could also add some test cases in FindCommandTest.java as well where you can test the command as a whole. Other than that the code LGTM!

**Pull request merged**
