### PR TITLE
UI rework

### PR DESCRIPTION
**Pull request by jq1836**
## Documentation
- [x] User Guide
- [X] Developer Guide
- [X] Javadocs

### Sections updated under UG

- NIL

### Sections updated under DG

- NIL

### Classes with Javadocs update

- `MainWindow.java`
- `ResidentTableView.java`

### Misc.

- `Ui.png`

# Todo:
- [x] Change `HelpWindow` UG link
- [x] Add index column to `PersonTableView`
- [x] Remove `File` tab
- [x] Change icon to RC4 icon
- [x] Removed `INDEX` header
- [x] Resized `INDEX` column
- [x] Add Resident fields when `Resident` class is ready
- [x] Remove `PersonListPanel.java`, `PersonCard.java`, `PersonListCard.fxml`
- [x] Update `Index.md` with the revised GUI 

# Proposed future changes:
- Make `TableCell` wrap
- Issue #79 

## Current GUI
image

### CODE REVIEW

**Review by jq1836 — COMMENTED** [review]
LGTM! This PR was done by @nealetham, but created by me. As I am unable to approve the PR, I will get @nealetham to approve on my behalf.

**Review by nseah21 — APPROVED** [review]
Changes to UI look good. Approved.

**Review by alvinjiang1 — APPROVED** [review]
LGTM👌

**Review by nealetham — APPROVED** [review]
Approved on behalf of @jq1836

**Pull request merged**
